### ISSUE TITLE
Deadlinks to the demos in the readme 

### ISSUE THREAD

**Issue by krejov100** [intel/depth-camera-web-demo#18]
Hi, I wanted to make you aware of the demos that are linked to in the readme are currently 404ing.
example Link:
https://01org.github.io/depth-camera-web-demo/depthdemo.html

**Comment by silqwer** [comment]
> 안녕하세요, readme에 연결된 데모가 현재 404임을 알고 싶습니다.
> 링크 예 :
> https://01org.github.io/depth-camera-web-demo/depthdemo.html

01org → intel
https://intel.github.io/depth-camera-web-demo/depthdemo.html

**Comment by ttoivone** [comment]
Hi, thanks, we already are aware of the issue. The previous maintainer is not anymore maintaining the code and nobody else has yet merge permissions to the repository. We're working in it.

**Comment by riju** [comment]
The links should be fixed now, else for backup check https://riju.github.io/depth-camera-web-demo/
