### ISSUE TITLE
Depth Capture Demo, Background removal demo is not working

### ISSUE THREAD

**Issue by silqwer** [intel/depth-camera-web-demo#19]
Hi, i used D415.

this demo is not working.

[](https://intel.github.io/depth-camera-web-demo/depthdemo.html)

![image](https://user-images.githubusercontent.com/4418255/64397114-02faa600-d09b-11e9-994b-6e8a0ee7c28d.png)

please help me.

**Comment by ttoivone** [comment]
Could you please open the Console in Chrome (with Ctrl+Shift+I, for instance) and check if you get some error messages? If so, please copy-and-paste them here to help debugging.

**Comment by silqwer** [comment]
This is the picture that chose the rgp camera.
![image](https://user-images.githubusercontent.com/4418255/64656129-5b4df100-d469-11e9-8c52-eca03f36ef21.png)

This error was resolved on the local host.
![image](https://user-images.githubusercontent.com/4418255/64656422-5473ae00-d46a-11e9-9dda-5b01ab207966.png)

But it doesn't work as it does below.

This is the picture that chose the depth camera.
![image](https://user-images.githubusercontent.com/4418255/64656149-7456a200-d469-11e9-9b6f-d8c3a2370181.png)

select background video or background color.
![image](https://user-images.githubusercontent.com/4418255/64656243-cdbed100-d469-11e9-8f50-2ad36ed12c73.png)
![image](https://user-images.githubusercontent.com/4418255/64656245-d2838500-d469-11e9-8c30-eb5394b5418f.png)

Thank you for your answer. Please help me.

**Comment by ttoivone** [comment]
If you select the depth stream from the menu and click on the "Render depth" tab, can you see the depth stream then?

I made some patches which might fix the background removal issue (patch "Quick hack to fix background removal"). They're in my forked repository. Please try them by going to address
   https://ttoivone.github.io/depth-camera-web-demo/depthdemo.html
with Chrome. Please select the depth stream from the menu, not RGB. It is promising that in the above images if you select the depth stream there are no serious error messages. 

Still I don't understand why you get the error "Error: No realsense camera connected." You could also try to give option --enable-blink-features=MediaCaptureDepthVideoKind to Chrome, although I suspect it doesn't make any difference.

**Comment by silqwer** [comment]
yes i can see render stream. depth stream is working.
![image](https://user-images.githubusercontent.com/4418255/64928551-cc6c1a80-d854-11e9-96df-835801fb8a8b.png)

and I set up experimental web platform features.
![image](https://user-images.githubusercontent.com/4418255/64928594-69c74e80-d855-11e9-80e9-0f07d54e351a.png)

but... background removal tab is same. 
![image](https://user-images.githubusercontent.com/4418255/64928681-992a8b00-d856-11e9-9ca9-b522a2df3779.png)
![image](https://user-images.githubusercontent.com/4418255/64928685-b0697880-d856-11e9-953f-2dfbbaa5f202.png)
![image](https://user-images.githubusercontent.com/4418255/64928691-bcedd100-d856-11e9-9fba-4e51f5fcb94d.png)

Can you show me the working background removal demo?

Thank you for your answer.

**Comment by ttoivone** [comment]
I tested Chromium versions 75 (Ubuntu bundled version) and 78 (self-compiled from repository) and for me both work (except the latter doesn't show the video, but solid background works). I don't get the error "GL_INVALID_OPERATION: Feedback loop formed between Framebuffer and active Texture.". This could be the serious error that you have but unfortunately I couldn't reproduce it. I'll check the source if I find anything wrong in it. 
In the meantime, could you please try to reset your Chrome configuration and try again? (In Linux you can remove file ~/.config/chromium/Default/Preferences). First you could disable the WebVRemu extension which is see in your console messages. I suggest also trying on another computer.
Here's a screenshot where it works in my computer:
![screenshot](https://user-images.githubusercontent.com/25431041/64987003-ec412400-d8d0-11e9-84d9-93c42689a763.png)

**Comment by ttoivone** [comment]
I pushed couple of more patches to remove some textures which were not anymore used in the shaders. Please try if this change would fix your issues:
https://ttoivone.github.io/depth-camera-web-demo/depthdemo.html
Please hold down "shift" and click on Refresh to ensure that Chrome downloads the latest version (instead of using old version from web page cache).

**Comment by silqwer** [comment]
Thank you for your answer.
backgound removal demo is working!!

![image](https://user-images.githubusercontent.com/4418255/64999826-27207780-d924-11e9-8ecb-3cc07436b832.png)
![image](https://user-images.githubusercontent.com/4418255/64999832-2f78b280-d924-11e9-986d-b5587e5c1627.png)

I don’t have the words to thank you for this.
I owe you one.

**Comment by ttoivone** [comment]
Happy to hear that! :-)
