### ISSUE TITLE
New camera support / mobile support

### ISSUE THREAD

**Issue by TotallWAR** [intel/depth-camera-web-demo#20]
Hey!
I checked depthdemo.html with my phone Xiaomi Redmi note 8 pro which has depth sensor.

I just removed condition ```track.label.indexOf("RealSense")``` and it seems to work..
I used current chrome version for mobile.
So the question is next: it's written [here](https://www.chromestatus.com/feature/5713419084759040) that depth sensor is still in development. It means i can't use in production web app which gets cloud of points because of future probably changes, can i?

**Comment by riju** [comment]
I don't expect the API shape to change drastically. As depth sensors become more prevalent over time and we can delight users with more compelling use cases, we can think of promoting it to stable. Till then it should remain behind a flag.
