### ISSUE TITLE
Typing in air with D435

### ISSUE THREAD

**Issue by yonglizhong** [intel/depth-camera-web-demo#23]
Hi, I have recently purchased a Real Sense camera D435 and am interested in trying out the typing in air function. I have git clone the repo and tried opening the html link on Google Chrome but other than the keyboard, nothing else is shown although I was requested to allow access for my camera. The demo links are also dead, was wondering if there are any more maintenance to this repo. Thank you

**Comment by yonglizhong** [comment]
![Screenshot from 2019-12-10 14-34-59](https://user-images.githubusercontent.com/55392228/70533907-4eb96180-1b5a-11ea-89eb-0805a5d1e30b.png)

**Comment by riju** [comment]
The demo links should work now, else for backup here's a fork - https://riju.github.io/depth-camera-web-demo/
