### ISSUE TITLE
Detecting Realsense camera in Chrome on Mac OS

### ISSUE THREAD

**Issue by alifeinbinary** [intel/depth-camera-web-demo#25]
I'm using Chrome 80 on Mac OS Mojave and the D415 that I have plugged into a USB3 port isn't populated to the dropdown list. [I noticed in this article](https://01.org/chromium/blogs/astojilj/2017/depth-camera-capture-html5) that says, as of when the article was written (2017), work was being done to support the depth cameras on OSX. I'm wondering if any progress is being made on that? I'm developing software for Realsense cameras on Mac OS but deploying on an embedding Linux system. The Linux system detects the camera just fine. I've built and installed the from the librealsense repo on both systems. Anyone had any luck with this?

**Comment by riju** [comment]
You should not need librealsense to use the depth stream work on Linux/CrOS or Windows(MediaFoundation backend). We [__do not_ support_](https://bugs.chromium.org/p/chromium/issues/detail?id=680906) depth capture for OSX.
