### ISSUE TITLE
Can you please get your links working?  How to find the device in Windows 7?

### ISSUE THREAD

**Issue by RichardKCollins** [intel/depth-camera-web-demo#26]
At https://github.com/intel/depth-camera-web-demo these links are broken:

Run Live Demo - https://01org.github.io/depth-camera-web-demo/typing_in_the_air/front_capture_typing.html

Depth Camera Capture in HTML5 - https://01.org/zh/node/5101

AR marker detection on GPU using WebGL - https://01.org/zh/node/26012

Background removal with Intel Realsense Depth Camera, WebRTC and WEbGL - https://01.org/zh/node/28902

Background removal using TensorFlow.js - https://01.org/zh/node/29971

I tried this and it won't list the RealSense devices.  The camera device drivers are listed under USB devices and the RealSense Viewer sees and can use the devices. The viewer is not running when I look at the device list.

navigator.mediaDevices.enumerateDevices().then(ListDevices);
	return;
	
	function ListDevices(Devices)
	{
		for (var i in Devices)
		{
			var device = Devices[i];
		}
		return;
	}

Thanks,
Richard Collins, The Internet Foundation

**Comment by riju** [comment]
The links should be fixed now, else for backup check https://riju.github.io/depth-camera-web-demo/

**Comment by riju** [comment]
I have not tried on Windows 7, but Chrome on Windows has 2 media back ends, the default MediaFoundation should work but the legacy DirectShow backend (behind a flag  `--disable-features=MediaFoundationVideoCapture`) was crashing for gUM enumerateDevices(). 
We fixed it sometime back [Details](https://bugs.chromium.org/p/chromium/issues/detail?id=1043952).
