### ISSUE TITLE
SR300 doesn't work on Chrome OS (WAS: and on Linux)

### ISSUE THREAD

**Issue by Christywl** [intel/depth-camera-web-demo#6]
Using `Intel RealSense SR300 camera`, test https://01org.github.io/depth-camera-web-demo/depthdemo.html on `Linux 16.04 Chrome 61.0.3153.4` and `Chrome OS Chrome 61.0.3147.0`, the video doesn't display, it only shows black:
![sr300](https://user-images.githubusercontent.com/20039821/28398549-3de797d0-6d3a-11e7-8309-209610e728ba.png)

**Comment by astojilj** [comment]
This camera requires specific installation on Linux/ChromeOS - patching the uvc kernel module:
https://github.com/IntelRealSense/librealsense/blob/master/doc/installation.md
Please reopen if after following the installation the problem is still visible.

**Comment by Christywl** [comment]
@astojilj , I see RealSense doesn't support Chrome OS in https://github.com/IntelRealSense/librealsense. So what should I do on Chrome OS? 
![xcuz0274](https://user-images.githubusercontent.com/20039821/29652832-e6c6d25c-88d9-11e7-85d1-b3a54604e02b.jpg)

**Comment by astojilj** [comment]
Reopening and renaming to "SR300 doesn't support Chrome OS". Linux support is fine with patched kernel.
Let me see if and how soon we can resolve this.

**Comment by astojilj** [comment]
@gabrielstuff reported the same issue #10.

**Comment by Christywl** [comment]
@astojilj , I run these four demos with DS435 RealSense Camera for Chrome 69 on Chrome OS, all of them don't work. Here are the screenshots:
pointcloud:
![pointcloud](https://user-images.githubusercontent.com/20039821/40900987-c12952ca-6800-11e8-98fa-25e9463702e8.png)
typing_in_the_air:
![typing_in_the_air](https://user-images.githubusercontent.com/20039821/40900989-c1563894-6800-11e8-8efd-b3745e6b9a64.png)
depthdemo:
![depthdemo](https://user-images.githubusercontent.com/20039821/40900985-c0ccc99c-6800-11e8-944b-74064e5587c9.png)
gesture:
![gesture](https://user-images.githubusercontent.com/20039821/40900986-c0fc5798-6800-11e8-8388-55e587d6e108.png)

**Comment by jkeys-ecg-nmsu** [comment]
@astojilj has this issue been resolved? We want to use Intel depth camera streaming to ChromOE for a product.

**Comment by astojilj** [comment]
@jkeys-ecg-nmsu 
There is an issue only with SR300.
All the recent cameras: https://software.intel.com/en-us/realsense/d400 should be supported.

@Christywl , @arskama, @ttoivone could provide help in verifying this and answering further questions.

**Comment by ttoivone** [comment]
@jkeys-ecg-nmsu could you please confirm which depth camera you're using, is it the SR300? Which ChromeOS/Chrome browser version? Can you get the camera to work on other platforms (eg. Ubuntu), just to ensure that the problem is particularly with ChromeOS.

**Comment by jkeys-ecg-nmsu** [comment]
Hey @astojilj @ttoivone sorry for the late response.

I was confused by which models we're using, we have D4xx series cameras. (I saw Realsense doesn't work on ChromeOS and panicked.) We are using Pixel Slate chromebooks with the latest firmware and ChromeOS. 

I have had a hard time getting the color stream to work on Windows or Ubuntu, even when scoping down the getUserMedia constraints to exactly require a color stream. The heuristics in this library are interesting though, I may have more success getting access to color AND depth streams (although admittedly we mostly need the depth stream) using the heuristics presented here until the MediaStreams API is mature.

**Comment by ttoivone** [comment]
Hi, finally I got Slate into my hands and checked what is the problem.

One line workaround: delete/rename files /usr/bin/cros_camera_* and reboot

Longer instructions and explanation:

Chrome Browser on ChromeOS does not usually use directly /dev/video* devices (V4L2) API,
but there is a camera HAL between. If the HAL is running, the browser gets the list of connected
cameras from HAL. That's the reason why the camera identification strings are different;
with V4L2 API navigator.mediaDevices.enumerateDevices() gives you strings which include,
for example, the USB ids, but if running with the HAL enabled, it simply gives Front/Back/External
camera. Also the HAL doesn't support the depth cameras so it won't provide the depth streams
to the browser at all.

Fortunately, the Chrome browser has a fallback to V4L2 API if the camera HAL is not running.
By renaming/deleting the above files, camera HAL doesn't start at all, the browser falls back
to using directly the V4L2 API, and it works. Unfortunately, the internal cameras won't work
anymore on Slate: those are MIPI based cameras accessed through Intel IPU3 driver and they
require the userspace HAL.

The proper fix is to add the depth stream support to both ChromeOS camera HAL and the
corresponding backend in the Chrome browser. 

Some more detailed instructions:
Enable developer mode by pressing volume up+down+power for 7 seconds
Reboot, start crosh shell with Ctrl+Alt+T. Give commands:

shell
sudo su
/usr/share/vboot/bin/make_dev_ssd.sh --remove_rootfs_verification --partitions 4

This makes the root partition writable

cd /usr/bin
mv cros_camera_service cros_camera_service.orig
mv cros_camera_algo cros_camera_algo.orig

Reboot. Now the camera should work, at least D415 works.
