### ISSUE TITLE
Typing_in_the_air Demo doesn't work fine on R200

### ISSUE THREAD

**Issue by Christywl** [intel/depth-camera-web-demo#8]
Test https://01org.github.io/depth-camera-web-demo/typing_in_the_air/front_capture_typing.html on `Windows 10 Chrome Canary 61.0.3159.0`, `Linux 16.04 Chrome 61.0.3153.4` and `Chrome OS Chrome 61.0.3147.0`, I find two issues when using `Intel RealSense R200 camera`:
1. If no hands close to the keyboard and other things move, it may be recognized a key-press. 
2. The gesture recognition doesn't work fine as SR300.
![windows_r200_3](https://user-images.githubusercontent.com/20039821/28400877-9caea14c-6d48-11e7-9b33-0a2accf1af1d.png)

**Comment by astojilj** [comment]
Typing in the air demo is primarily targeting SR300 based cameras - near range with less noise.
We could probably just update the error message and don't allow the usage of R200.

**Comment by Christywl** [comment]
Updated info: similar issue for ZR300
![zr300-3](https://user-images.githubusercontent.com/20039821/30629676-bb8af294-9e0f-11e7-885a-9df087a90e00.png)
